import { Video, Comment, Channel, User } from './types';

export const INITIAL_CHANNELS: Channel[] = [
  {
    id: 'chan-1',
    name: 'TechWave',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
    subscribersCount: 124000,
    isSubscribed: false,
  },
  {
    id: 'chan-2',
    name: 'CreativePixel',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    subscribersCount: 89000,
    isSubscribed: true,
  },
  {
    id: 'chan-3',
    name: 'EcoVentures',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
    subscribersCount: 215000,
    isSubscribed: false,
  },
  {
    id: 'chan-4',
    name: 'GamingArcade',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    subscribersCount: 432000,
    isSubscribed: false,
  },
  {
    id: 'chan-5',
    name: 'CodeCraft',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
    subscribersCount: 512000,
    isSubscribed: true,
  },
];

export const INITIAL_VIDEOS: Video[] = [
  {
    id: 'vid-1',
    title: 'Building a Full-Stack Web Application From Scratch in 2026',
    description: 'Learn how to architect, develop, and deploy a responsive, production-ready web application using modern technologies including React, Tailwind CSS, Express, and high-performance databases. This course walks you through state management, database schema design, server integrations, and deployment configurations on cloud infrastructure.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=640&q=80',
    duration: '9:56',
    views: 145000,
    uploadedAt: '2 days ago',
    category: 'Coding',
    channelId: 'chan-5',
    channelName: 'CodeCraft',
    channelAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 8200,
    dislikes: 120,
    likeStatus: 'none',
  },
  {
    id: 'vid-2',
    title: 'The Future of AI and Cloud Compute - In-Depth Analysis',
    description: 'Explore the next frontier of artificial intelligence, edge computing, and elastic server clusters. In this video, we dissect the shifting landscape of hardware acceleration, machine learning compilers, and remote execution frameworks designed to run heavy inference at scale.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=640&q=80',
    duration: '10:53',
    views: 92000,
    uploadedAt: '1 week ago',
    category: 'Tech',
    channelId: 'chan-1',
    channelName: 'TechWave',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 5400,
    dislikes: 45,
    likeStatus: 'none',
  },
  {
    id: 'vid-3',
    title: 'Minimalist UX Design Principles: Creating Clean Interfaces',
    description: 'A visual walkthrough of minimalist interface guidelines. Learn how to leverage generous padding, bold typography scales, micro-interactions, and balanced whitespace to create high-conversion layouts that delight users. We review iconic Swiss modernism projects and apply their tenets to SaaS web products.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=640&q=80',
    duration: '14:12',
    views: 64000,
    uploadedAt: '5 days ago',
    category: 'Design',
    channelId: 'chan-2',
    channelName: 'CreativePixel',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 3100,
    dislikes: 18,
    likeStatus: 'none',
  },
  {
    id: 'vid-4',
    title: 'Deep Forest Canopy & Stream Sounds - 10 Hours Nature Loop',
    description: 'Escape into a lush, remote forest canopy, accompanied by the gentle murmurs of an pristine mountain stream. Designed for deep relaxation, yoga, studying, or clearing your mind. Recorded in ultra-high fidelity stereophonic audio.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=640&q=80',
    duration: '5:43',
    views: 312000,
    uploadedAt: '1 month ago',
    category: 'Nature',
    channelId: 'chan-3',
    channelName: 'EcoVentures',
    channelAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 18000,
    dislikes: 95,
    likeStatus: 'none',
  },
  {
    id: 'vid-5',
    title: 'Ambient Lo-Fi Beats for Coding, Designing & Late Night Study',
    description: 'Tune into our premier late-night lo-fi workspace broadcast. Curated instrumentals, warm vinyl crackles, dynamic synth-pads, and smooth basslines optimized for entering the flow state. Grab a coffee, settle in, and let’s construct something amazing.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=640&q=80',
    duration: '15:02',
    views: 185000,
    uploadedAt: '3 days ago',
    category: 'Music',
    channelId: 'chan-2',
    channelName: 'CreativePixel',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 9200,
    dislikes: 30,
    likeStatus: 'none',
  },
  {
    id: 'vid-6',
    title: 'Competitive Speedrunning in Cyberpunk Arcades',
    description: 'A fast-paced review of arcade gaming history, focusing on speedrunning dynamics, input optimizations, and Frame-Perfect routing. We interview world record holders and explore physical retro game parlors in Akihabara with high contrast ambient light fixtures.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=640&q=80',
    duration: '8:15',
    views: 45000,
    uploadedAt: '12 hours ago',
    category: 'Gaming',
    channelId: 'chan-4',
    channelName: 'GamingArcade',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 2100,
    dislikes: 12,
    likeStatus: 'none',
  },
  {
    id: 'vid-7',
    title: 'Sci-Fi Synth Orchestration & Space Odyssey Soundscapes',
    description: 'An immersive collection of modern modular synth scores. Witness a cinematic exploration of space frontiers, alien planet orbits, and black hole distortion fields. Styled for developers, writers, and sci-fi enthusiasts.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=640&q=80',
    duration: '12:14',
    views: 128000,
    uploadedAt: '3 weeks ago',
    category: 'Music',
    channelId: 'chan-1',
    channelName: 'TechWave',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 7100,
    dislikes: 41,
    likeStatus: 'none',
  },
  {
    id: 'vid-8',
    title: 'The Rise of Next-Gen Retro Gaming Handhelds',
    description: 'In this console review, we test five brand new Linux and Android powered retro gaming handhelds. We test emulation performance across multiple platforms, checking battery curves, screen panels, and ergonomics of premium plastic and metal shells.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=640&q=80',
    duration: '11:05',
    views: 75000,
    uploadedAt: '4 days ago',
    category: 'Gaming',
    channelId: 'chan-4',
    channelName: 'GamingArcade',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 4100,
    dislikes: 22,
    likeStatus: 'none',
  },
  {
    id: 'short-1',
    title: 'Typing code at 150 WPM on a mechanical keyboard 💻🔥',
    description: 'Witness high-speed responsive programming in real-time. Mastering the flow state, custom keycaps, and tactile mechanical switch soundscapes designed for programmers.',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-programmer-typing-on-a-keyboard-40545-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=640&q=80',
    duration: '0:32',
    views: 89000,
    uploadedAt: '1 day ago',
    category: 'Shorts',
    channelId: 'chan-5',
    channelName: 'CodeCraft',
    channelAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 6200,
    dislikes: 12,
    likeStatus: 'none',
    isShort: true,
  } as any,
  {
    id: 'short-2',
    title: 'Playing legendary retro game in 2026 arcade parlor 🎮🕹️',
    description: 'An immersive vertical walkthrough of tactical retro frame movements, responsive button layouts, and the colorful cabinet glow of retro game halls in Akihabara.',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-playing-retro-arcade-video-game-41829-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=640&q=80',
    duration: '0:24',
    views: 124000,
    uploadedAt: '4 hours ago',
    category: 'Shorts',
    channelId: 'chan-4',
    channelName: 'GamingArcade',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 9300,
    dislikes: 18,
    likeStatus: 'none',
    isShort: true,
  } as any,
  {
    id: 'short-3',
    title: 'Stunning summer sky canopy view in nature forest 🌿✨',
    description: 'A relaxing vertical escape. Experience the slow-motion dancing of leaves, high-contrast forest light beams, and pure sky aesthetics.',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-tree-branches-and-leaves-low-angle-40913-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=640&q=80',
    duration: '0:15',
    views: 45000,
    uploadedAt: '2 days ago',
    category: 'Shorts',
    channelId: 'chan-3',
    channelName: 'EcoVentures',
    channelAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 3100,
    dislikes: 5,
    likeStatus: 'none',
    isShort: true,
  } as any,
  {
    id: 'short-4',
    title: 'Satisfying close-up view of wild ocean waves crashing 🌊💙',
    description: 'Lose yourself in the continuous motion of deep blue crystal waters breaking on the coastline. Beautifully recorded in high frame rate.',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-breaking-in-the-ocean-1527-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=640&q=80',
    duration: '0:18',
    views: 67000,
    uploadedAt: '3 days ago',
    category: 'Shorts',
    channelId: 'chan-3',
    channelName: 'EcoVentures',
    channelAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
    likes: 5200,
    dislikes: 9,
    likeStatus: 'none',
    isShort: true,
  } as any
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'short-comm-1',
    videoId: 'short-1',
    userName: 'Ziyad Al-Harbi',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'صوت الكيبورد مريح جداً للأعصاب! ما هو نوع السويتشات المستخدمة؟ 😍',
    uploadedAt: '2 hours ago',
    likes: 42,
  },
  {
    id: 'short-comm-2',
    videoId: 'short-1',
    userName: 'Nadia El-Masry',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'Wow, typing at 150 WPM while designing is true wizardry. Amazing mechanical switches.',
    uploadedAt: '1 hour ago',
    likes: 12,
  },
  {
    id: 'short-comm-3',
    videoId: 'short-2',
    userName: 'Karim Saeed',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'رجعتني لأيام الطفولة الجميلة مع ألعاب الآركيد! تفاصيل مذهلة.',
    uploadedAt: '3 hours ago',
    likes: 28,
  },
  {
    id: 'short-comm-4',
    videoId: 'short-3',
    userName: 'Fatima Al-Otaibi',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'سبحان الله، لقطة تريح النفس وتجلب السلام والسكينة لقلب المشاهد.',
    uploadedAt: '1 day ago',
    likes: 64,
  },
  {
    id: 'comm-1',
    videoId: 'vid-1',
    userName: 'Sarah Jenkins',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'This is arguably the absolute best breakdown of modern full-stack web architecture I have ever seen. Simple, robust, and completely functional. The explanation of DB index configurations saved my team weeks of troubleshooting!',
    uploadedAt: '3 hours ago',
    likes: 342,
  },
  {
    id: 'comm-2',
    videoId: 'vid-1',
    userName: 'Alex Rivers',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'Absolutely loving the UI layout styling tips! I immediately replaced our default cards with high-contrast borders and spacious margins. Incredible value.',
    uploadedAt: '1 day ago',
    likes: 84,
  },
  {
    id: 'comm-3',
    videoId: 'vid-2',
    userName: 'Liam Chen',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'Mind-blowing analysis of inference models at the edge. The way custom hardware accelerators are changing the cloud compute topology is a massive shift.',
    uploadedAt: '2 days ago',
    likes: 121,
  },
  {
    id: 'comm-4',
    videoId: 'vid-3',
    userName: 'Elena Petrova',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'Swiss Modernism paired with digital product interface layouts is such an under-explored space. Thank you for bringing structural rigor back to UI design.',
    uploadedAt: '4 days ago',
    likes: 156,
  },
  {
    id: 'comm-5',
    videoId: 'vid-4',
    userName: 'Marcus Aurelius',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=50&h=50&q=80',
    content: 'Perfect audio quality. I have this playing on my workspace speakers in the background while designing. It blocks out office clutter seamlessly.',
    uploadedAt: '2 weeks ago',
    likes: 412,
  },
];

export const CURRENT_USER: User = {
  id: 'usr-current',
  username: 'dev_architect',
  displayName: 'Lead System Architect',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80',
  email: 'myahia69@gmail.com',
};
